language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
script:
  - npm install
  - npm test
deploy:
  provider: script
  script: 
    - docker-compose build
    - bash docker_push
  on:
    branch: master