language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: build    
      script:
        - npm install
    - stage: unit-test 
      script:   
        - npm test
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t scouts-api .
        - docker images
        - docker tag scouts-api $DOCKER_USERNAME/scouts-api
        - docker push $DOCKER_USERNAME/scouts-api:rc1
