language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
addons:
  sonarcloud:
    organization: "vinaykp-github"
    token:
      secure: $SONAR_TOKEN
jobs:
  include:
    - stage: build    
      script:
        - npm install
    - stage: unit-test 
      script:   
        - npm test
    -stage: sonar scan
      script:
        - sonar-scanner
    - stage: int-test
      script:
        - docker -v
        - docker-compose up -d
        - sleep 30
        - echo "Start Integration test"
        - npm run test:int    
        - sleep 5
        - docker-compose down
    - stage: push docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t scouts-api .
        - docker images
        - docker tag scouts-api vinaykp/scouts-api
        - docker push vinaykp/scouts-api:latest


