language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
addons:
  sonarcloud:
    organization: "vinaykp-github" # the key of the org you chose at step #3
    token:
      secure: "$SONAR_TOKEN" # encrypted value of your token
jobs:
  include:
    - stage: build    
      script:
        - npm install
    - stage: unit-test 
      script:   
        - npm test
    - stage: code coverage     
      install:
        - npm install -g codecov
      script:
        - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
        - codecov    
    -stage: sonar scan
      script:
        - sonar-scanner    
    - stage: int-test
      script:
        - docker -v
        - docker-compose up -d
        - sleep 45
        - echo "Start Integration test"
        - npm run test:int    
        - sleep 10
        - docker-compose down
    - stage: push docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t scouts-api .
        - docker images
        - docker tag scouts-api vinaykp/scouts-api
        - docker push vinaykp/scouts-api:latest
notifications:
  email:
    recipients:
      - vinaykp@hotmail.com
    on_success: never # default: change
    on_failure: always # default: always
