version: '2'
services:
  mongo:
    container_name: scouts-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017" 
  app:
    container_name: scouts-api
    restart: always
    image: vinaykp/scouts-api:latest
    build: .
    command: >
      /bin/bash -c "
        sleep 30;
        npm start
        "
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
