version: '2'
services:
  mongo:
    container_name: scouts-mongo
    image: mongo:latest
    volumes:
      - ./data:/data/db
  app:
    container_name: scouts-api
    restart: always
    image: vinaykp/scouts-api:latest
    build: .
    command: 
      - sleep 15
      - npm start
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
